services:
  db:
    image: ankane/pgvector:latest # PostgreSQL + pgvector
    container_name: saribudolok_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: saribudolok_gis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d # Untuk inisialisasi PostGIS
    networks:
      - saribudolok_net

  redis:
    image: redis:alpine
    container_name: saribudolok_redis
    ports:
      - "6379:6379"
    networks:
      - saribudolok_net

networks:
  saribudolok_net:
    driver: bridge

volumes:
  postgres_data:
